import Head from 'next/head'
import Dashboard from '../Components/Dashboard'
import Footer from '../Components/Footer'
import SliderAudio from '../Components/SliderAudio'
import Title from '../Components/Title'
import Styles from '../styles/Home.module.css'


export default function Home() {
  const user = {
    id: 1,
    email: "remycottrez@gmail.com",
    name: "Rémy",
    isAdmin: true
  }

  return (
    <div className={Styles.body}>
      <Head>
        <title>NextBox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Styles.main}>
        <Title name={user.name} />
        {user.isAdmin ? (
          <>
            <p>Bienvenue superAdmin</p>
            <Dashboard />
          </>
        ) : (
          <p> Vous n&apos;avez pas de super pouvoir</p>
        )}
      </main>
      <SliderAudio />
      <Footer />
    </div>
  )
}
